create database easycart;
use easycart;

-- 1. Customers
CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    gender VARCHAR(20),
    age INT,
    city VARCHAR(50),
    state VARCHAR(50),
    registration_date DATE
);

-- 2. Customer Sessions
CREATE TABLE customer_sessions (
    session_id INT PRIMARY KEY,
    customer_id INT,
    session_date DATETIME,
    device_type VARCHAR(30),
    traffic_source VARCHAR(50),
    session_duration INT,
    pages_viewed INT,
    
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

-- 3. Brands
CREATE TABLE brands (
    brand_id INT PRIMARY KEY,
    brand_name VARCHAR(100) NOT NULL
);

-- 4. Categories
CREATE TABLE categories (
    category_id INT PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL
);

-- 5. Products
CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(150) NOT NULL,
    brand_id INT,
    category_id INT,
    selling_price DECIMAL(10,2),
    cost_price DECIMAL(10,2),
    launch_date DATE,
    
    FOREIGN KEY (brand_id) REFERENCES brands(brand_id),
    FOREIGN KEY (category_id) REFERENCES categories(category_id)
);

-- 6. Sellers
CREATE TABLE sellers (
    seller_id INT PRIMARY KEY,
    seller_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    state VARCHAR(50),
    seller_rating DECIMAL(3,2),
    join_date DATE
);

-- 7. Orders
CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    seller_id INT,
    order_date DATETIME,
    order_status VARCHAR(30),
    shipping_city VARCHAR(50),
    shipping_state VARCHAR(50),
    
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (seller_id) REFERENCES sellers(seller_id)
);

-- 8. Order Items
CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT,
    product_id INT,
    quantity INT,
    unit_price DECIMAL(10,2),
    discount DECIMAL(10,2),
    
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- 9. Payments
CREATE TABLE payments (
    payment_id INT PRIMARY KEY,
    order_id INT,
    payment_date DATETIME,
    payment_method VARCHAR(30),
    payment_status VARCHAR(30),
    amount DECIMAL(10,2),
    
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

-- 10. Warehouses
CREATE TABLE warehouses (
    warehouse_id INT PRIMARY KEY,
    warehouse_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    state VARCHAR(50),
    warehouse_capacity INT
);

-- 11. Shipments
CREATE TABLE shipments (
    shipment_id INT PRIMARY KEY,
    order_id INT,
    warehouse_id INT,
    shipping_date DATE,
    expected_delivery_date DATE,
    actual_delivery_date DATE,
    delivery_status VARCHAR(30),
    
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouses(warehouse_id)
);

-- 12. Returns
CREATE TABLE returns (
    return_id INT PRIMARY KEY,
    order_item_id INT,
    return_date DATE,
    return_reason VARCHAR(150),
    refund_amount DECIMAL(10,2),
    return_status VARCHAR(30),
    
    FOREIGN KEY (order_item_id) REFERENCES order_items(order_item_id)
);

-- 13. Reviews
CREATE TABLE reviews (
    review_id INT PRIMARY KEY,
    customer_id INT,
    product_id INT,
    rating INT,
    review_date DATE,
    review_text VARCHAR(500),
    
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

show tables;
select * from customers;
select * from brands;
select * from categories;
select * from products;
select * from sellers;
select * from warehouses;
select * from orders;
select * from order_items;
select * from payments;
select * from customer_sessions;
select * from shipments;
select * from returns;
select * from reviews;

use easycart;
-- Q1. Find the total number of orders and total revenue generated by EasyCart.
select 
count(distinct o.order_id) as total_orders,
sum(oi.quantity * oi.unit_price - oi.discount) as total_revenue
from orders o
join order_items oi
on o.order_id = oi.order_id;

-- Q2. Find the total quantity of products sold by EasyCart.
select sum(quantity) as total_product_sold
from order_items;

-- Q3. Find the average order value of EasyCart.
select 
 sum(oi.quantity * oi.unit_price - oi.discount) 
 / count(distinct o.order_id) as average_order_value
 from orders o 
 join order_items oi 
 on o.order_id = oi.order_id;
 
 -- Q4. Find the number of orders for each order status.
 select 
    order_status,
    count(order_id) as total_orders
    from orders
    group by order_status;
    
-- Q5. Find the monthly revenue generated by EasyCart.
select 
 month(o.order_date) as month,
 sum(oi.quantity * oi.unit_price - oi.discount) as monthly_revenue
 from orders o 
 join order_items oi 
 on o.order_id = oi.order_id
 group by month(o.order_date)
 order by month;
 
 -- Q6. Find the number of orders placed in each month.
 select
  month(order_date) as month,
  count(order_id) as total_orders
  from orders
  group by month(order_date)
  order by month;

-- Q7. Find the top 10 products based on total quantity sold.
select 
p.product_name,
sum(oi.quantity) as total_quantity_sold
from products p 
join order_items oi
on p.product_id = oi.product_id
group by p.product_id, p.product_name
order by total_quantity_sold desc
limit 10;  

-- Q8. Find the top 10 products based on total revenue generated.
select 
 p.product_name,
 sum(oi.quantity * oi.unit_price - oi.discount) as total_revenue
 from products p
 join order_items oi
 on p.product_id = oi.product_id
 group by p.product_id , p.product_name
 order by total_revenue desc
 limit 10;

-- Q9. Find the total revenue generated by each product category.
SELECT
    c.category_name,
    SUM(oi.quantity * oi.unit_price - oi.discount) AS total_revenue
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY c.category_id, c.category_name
ORDER BY total_revenue DESC;

-- Q10. Find the total quantity of products sold by each product category.
SELECT
    c.category_name,
    SUM(oi.quantity) AS total_quantity_sold
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY c.category_id, c.category_name
ORDER BY total_quantity_sold DESC;

-- Q11. Find the total revenue generated by each brand.
SELECT
    b.brand_name,
    SUM(oi.quantity * oi.unit_price - oi.discount) AS total_revenue
FROM brands b
JOIN products p
    ON b.brand_id = p.brand_id
JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY b.brand_id, b.brand_name
ORDER BY total_revenue DESC;


-- Q12. Find the average selling price of products in each category.
SELECT
    c.category_name,
    AVG(p.selling_price) AS average_selling_price
FROM categories c
JOIN products p
    ON c.category_id = p.category_id
GROUP BY c.category_id, c.category_name
ORDER BY average_selling_price DESC;

-- Q13. Find the top 10 customers based on their total spending.
SELECT
    c.customer_id,
    c.customer_name,
    SUM(oi.quantity * oi.unit_price - oi.discount) AS total_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.customer_name
ORDER BY SUM(oi.quantity * oi.unit_price - oi.discount) DESC
LIMIT 10;

-- Q14. Find the top 10 customers based on the number of orders placed.
SELECT
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_orders DESC
LIMIT 10;

-- Q15. Find customers who have placed more than one order.
SELECT
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(o.order_id) > 1
ORDER BY total_orders DESC;

-- Q16. Find the average spending of customers who have placed orders.
SELECT
    c.customer_id,
    c.customer_name,
    AVG(oi.quantity * oi.unit_price - oi.discount) AS average_spending
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_id, c.customer_name
ORDER BY average_spending DESC;

-- Q17. Find the number of customers in each city.
select 
 city,
 count(customer_id) as total_customer
 from customers
 group by city
 order by total_customer desc;
 
 
 -- Q18. Find the total revenue generated from each customer city.
 SELECT
    c.city,
    SUM(oi.quantity * oi.unit_price - oi.discount) AS total_revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.city
ORDER BY total_revenue DESC;

-- Q19. Find the total revenue generated by each seller.
SELECT
    s.seller_id,
    s.seller_name,
    SUM(oi.quantity * oi.unit_price - oi.discount) AS total_revenue
FROM sellers s
JOIN orders o
    ON s.seller_id = o.seller_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY s.seller_id, s.seller_name
ORDER BY total_revenue DESC;

-- Q20. Find the number of orders handled by each seller.
select 
s.seller_id,
s.seller_name,
count(o.order_id) as total_orders
from sellers s 
join orders o 
on s.seller_id = o.seller_id
group by s.seller_id,s.seller_name
order by total_orders desc;

-- Q21. Compare each seller's rating with their total revenue.
SELECT
    s.seller_id,
    s.seller_name,
    s.seller_rating,
    SUM(oi.quantity * oi.unit_price - oi.discount) AS total_revenue
FROM sellers s
JOIN orders o
    ON s.seller_id = o.seller_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY s.seller_id, s.seller_name, s.seller_rating
ORDER BY total_revenue DESC;

-- Q22. Find the average delivery time for EasyCart orders.
select 
    avg(DATEDIFF(actual_delivery_date,shipping_date)) as average_delivery
    from shipments
    where actual_delivery_date IS NOT NULL;
    
    
-- Q23. Find the number of delayed shipments.
-- A shipment is delayed when the actual delivery date is later than the expected delivery date.
select 
   count(shipment_id) as delayed_shipments
   from shipments
   where actual_delivery_date > expected_delivery_date;
   
-- Q24. Find the number of shipments handled by each warehouse
-- and count how many shipments were delivered successfully.
SELECT
    w.warehouse_id,
    w.warehouse_name,
    COUNT(s.shipment_id) AS total_shipments,
    SUM(CASE
        WHEN s.delivery_status = 'Delivered' THEN 1
        ELSE 0
    END) AS delivered_shipments
FROM warehouses w
JOIN shipments s
    ON w.warehouse_id = s.warehouse_id
GROUP BY w.warehouse_id, w.warehouse_name
ORDER BY delivered_shipments DESC;


-- Q25. Find the number of returned products for each return reason.
-- Also calculate the total refund amount for each reason.
select  
   return_reason,
   count(return_id) as total_return,
   sum(refund_amount) as total_refund_amount
   from returns
   group by return_reason
   order by total_return desc;

-- Q26. Rank all products based on their total revenue.
-- Highest revenue product should get Rank 1.
select 
  p.product_id,
  p.product_name,
  sum(oi.quantity * oi.unit_price - oi.discount) as total_revenue,
  rank() over(
    order by sum(oi.quantity * oi.unit_price - oi.discount) desc 
      ) as revenue_rank
 from products p 
 join order_items oi
   on p.product_id = oi.product_id
   group by 
     p.product_id,
     p.product_name
 order by revenue_rank;
 
 -- Q27. Rank products based on their selling price using DENSE_RANK().
-- Highest selling price should get Rank 1.
select 
  product_id,
  product_name,
  selling_price,
  DENSE_RANK() OVER(
	 order by selling_price desc
     ) as price_rank
  from products
  order by price_rank;
  
-- Q28. Find the monthly revenue and compare it with the previous month's revenue.
with monthly_revenue as (
     select 
       month(o.order_date) as month,
       sum(oi.quantity * oi.unit_price - oi.discount) as monthly_revenue
       from orders o 
       join order_items oi 
       on o.order_id = oi.order_id
       group by month(o.order_date)
      )
      
      select 
       month,
       monthly_revenue,
       LAG(monthly_revenue) over(
         order by month
         ) as previous_month_revenue
		from monthly_revenue
        order by month;
        
-- Q29. Find the monthly revenue and calculate the running (cumulative) revenue.
-- Running Revenue = Current Month Revenue + All Previous Months Revenue

WITH monthly_revenue AS (
    SELECT
        MONTH(o.order_date) AS month,
        SUM(oi.quantity * oi.unit_price - oi.discount) AS monthly_revenue
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY MONTH(o.order_date)
)

SELECT
    month,
    monthly_revenue,
    SUM(monthly_revenue) OVER (
        ORDER BY month
    ) AS running_revenue

FROM monthly_revenue
ORDER BY month;


-- Q30. Find customer-wise performance and classify customers based on their total spending.
-- Spending = (Quantity × Unit Price) - Discount
--
-- Classification:
-- Spending >= 20,000  → High Value
-- Spending >= 10,000  → Medium Value
-- Spending < 10,000   → Low Value
WITH customer_spending AS (
    SELECT
        c.customer_id,
        c.customer_name,
        COUNT(DISTINCT o.order_id) AS total_orders,
        SUM(oi.quantity * oi.unit_price - oi.discount) AS total_spending
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        c.customer_id,
        c.customer_name
)

SELECT
    customer_id,
    customer_name,
    total_orders,
    total_spending,
    CASE
        WHEN total_spending >= 20000 THEN 'High Value'
        WHEN total_spending >= 10000 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_segment
FROM customer_spending
ORDER BY total_spending DESC;





